# Generated by Django 4.2.29 on 2026-03-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='budget_level',
            field=models.CharField(choices=[('budget', 'Budget'), ('medium', 'Medium'), ('luxury', 'Luxury')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
